name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: George-Ogden/actions/.github/workflows/lint.yaml@v3.4.1

  cargo:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - name: Check
        run: |
          cargo check

      - name: Format
        run: |
          cargo fmt

      - name: Lint
        run: |
          cargo clippy -- -D warnings -W clippy::pedantic
