name: Automated Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write
  issues: read

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Clone actions repository
        run: |
          git clone https://github.com/George-Ogden/actions.git /tmp/external-repo

      - name: Read new version
        run: |
          NEW_VERSION=$(cat /tmp/external-repo/version.txt)
          echo "New version: '$NEW_VERSION'"
          echo "VERSION=${NEW_VERSION}" >> "$GITHUB_ENV"

      - name: Update action files
        run: |
          find .github -name "*.yaml" -exec sed -i "/George-Ogden\/actions\/.github\/workflows/s/@.*$/@v${{ env.VERSION }}/" {} \;

      - name: Create PR
        uses: ./.github/actions/commit-and-pr
        with:
          branch: "update-version-${{ env.VERSION }}"
          commit-message: "Automated actions version update"
          pr-title: "Automated Actions Version Sync"
          pr-body: "Update actions version to ${{ env.VERSION }}"
          token: ${{ secrets.PAT_TOKEN }}

  autoupdate-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install uv
          uv pip install pyyaml --system
          uv tool install prek

      - name: Run pre-commit autoupdate
        run: |
          prek autoupdate
          prek autoupdate -c python.pre-commit-config.yaml
          prek autoupdate -c rust.pre-commit-config.yaml
          prek autoupdate -c text.pre-commit-config.yaml

      - name: Update Ruff version in requirements-dev.txt
        run: |
          RUFF_VERSION=$(python - <<'EOF'
          import yaml
          with open("python.pre-commit-config.yaml") as f:
              config = yaml.safe_load(f)
          [ruff_repo] = [repo for repo in config["repos"] if repo["repo"] == "https://github.com/astral-sh/ruff-pre-commit/"]
          version = ruff_repo["rev"]
          assert version.startswith("v")
          print(version.replace("v", "", count=1))
          EOF
          )

          sed -i "s/^ruff=.*\$/ruff==$RUFF_VERSION/" requirements-dev.txt

      - name: Create PR
        uses: ./.github/actions/commit-and-pr
        with:
          branch: pre-commit-autoupdate
          commit-message: "Automated pre-commit autoupdate"
          pr-title: "Automated Pre-Commit Autoupdate"
          pr-body: "Autoupdate pre-commit"
          token: ${{ secrets.PAT_TOKEN }}

  update-cargo-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Update all packages to latest versions
        run: |
          python - <<'EOF'
          import os
          import subprocess
          import tomllib

          with open("Cargo.toml", "rb") as f:
              cargo_toml = tomllib.load(f)

          for dependency_list in cargo_toml["dependencies"], cargo_toml["dev-dependencies"]:
              for name, details in dependency_list.items():
                  old_version = details if isinstance(details, str) else details["version"]
                  check_cmd = subprocess.run(
                      f"cargo info {name}",
                      stdout=subprocess.PIPE,
                      shell=True,
                      check=True,
                      env=os.environ | dict(CARGO_TERM_COLOR="auto"),
                  )
                  output = check_cmd.stdout.decode()
                  print(output)
                  [version] = [
                      line.split(":")[1].strip()
                      for line in output.splitlines()
                      if line.startswith("version:")
                  ]
                  subprocess.run(
                      f"sed -i Cargo.toml -e '/{name}/s/{old_version.replace('.', r'\.')}/{version}/'",
                      shell=True,
                      check=True,
                  )
          EOF

      - name: Create PR
        uses: ./.github/actions/commit-and-pr
        with:
          branch: cargo-packages-update
          commit-message: "Automated cargo packages update"
          pr-title: "Automated Cargo Packages Update"
          pr-body: ""
          token: ${{ secrets.PAT_TOKEN }}
